<a href="https://colab.research.google.com/github/RiteshopShrivastava/Support_Vector_Machine/blob/main/Assignment_SVM_Forestfires.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Classify the Size_Categorie using SVM**

month	month of the year: 'jan' to 'dec'

day	day of the week: 'mon' to 'sun'

FFMC	FFMC index from the FWI system: 18.7 to 96.20

DMC	DMC index from the FWI system: 1.1 to 291.3

DC	DC index from the FWI system: 7.9 to 860.6

ISI	ISI index from the FWI system: 0.0 to 56.10

temp	temperature in Celsius degrees: 2.2 to 33.30

RH	relative humidity in %: 15.0 to 100

wind	wind speed in km/h: 0.40 to 9.40

rain	outside rain in mm/m2 : 0.0 to 6.4

Size_Categorie 	the burned area of the forest ( Small , Large)

In [6]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [77]:
forest_df = pd.read_csv('forestfires.csv')

In [70]:
forest_df

month  day  FFMC    DMC  ...  monthnov  monthoct  monthsep  size_category
0     mar  fri  86.2   26.2  ...         0         0         0          small
1     oct  tue  90.6   35.4  ...         0         1         0          small
2     oct  sat  90.6   43.7  ...         0         1         0          small
3     mar  fri  91.7   33.3  ...         0         0         0          small
4     mar  sun  89.3   51.3  ...         0         0         0          small
..    ...  ...   ...    ...  ...       ...       ...       ...            ...
512   aug  sun  81.6   56.7  ...         0         0         0          large
513   aug  sun  81.6   56.7  ...         0         0         0          large
514   aug  sun  81.6   56.7  ...         0         0         0          large
515   aug  sat  94.4  146.0  ...         0         0         0          small
516   nov  tue  79.5    3.0  ...         1         0         0          small

[517 rows x 31 columns]

# **EDA**

In [78]:
forest_df1 = forest_df.drop(['month','day'], axis=1)

In [79]:
forest_df1

FFMC    DMC     DC   ISI  ...  monthnov  monthoct  monthsep  size_category
0    86.2   26.2   94.3   5.1  ...         0         0         0          small
1    90.6   35.4  669.1   6.7  ...         0         1         0          small
2    90.6   43.7  686.9   6.7  ...         0         1         0          small
3    91.7   33.3   77.5   9.0  ...         0         0         0          small
4    89.3   51.3  102.2   9.6  ...         0         0         0          small
..    ...    ...    ...   ...  ...       ...       ...       ...            ...
512  81.6   56.7  665.6   1.9  ...         0         0         0          large
513  81.6   56.7  665.6   1.9  ...         0         0         0          large
514  81.6   56.7  665.6   1.9  ...         0         0         0          large
515  94.4  146.0  614.7  11.3  ...         0         0         0          small
516  79.5    3.0  106.7   1.1  ...         1         0         0          small

[517 rows x 29 columns]

**Preprocessing - Label Encoding**

In [80]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
forest_df1['size_category']= label_encoder.fit_transform(forest_df1['size_category'])

In [81]:
forest_df1

FFMC    DMC     DC   ISI  ...  monthnov  monthoct  monthsep  size_category
0    86.2   26.2   94.3   5.1  ...         0         0         0              1
1    90.6   35.4  669.1   6.7  ...         0         1         0              1
2    90.6   43.7  686.9   6.7  ...         0         1         0              1
3    91.7   33.3   77.5   9.0  ...         0         0         0              1
4    89.3   51.3  102.2   9.6  ...         0         0         0              1
..    ...    ...    ...   ...  ...       ...       ...       ...            ...
512  81.6   56.7  665.6   1.9  ...         0         0         0              0
513  81.6   56.7  665.6   1.9  ...         0         0         0              0
514  81.6   56.7  665.6   1.9  ...         0         0         0              0
515  94.4  146.0  614.7  11.3  ...         0         0         0              1
516  79.5    3.0  106.7   1.1  ...         1         0         0              1

[517 rows x 29 columns]

**Drop duplicate rows**

In [82]:
forest_df1.duplicated().sum()

8

In [83]:
forest_df2= forest_df1.drop_duplicates()

In [84]:
forest_df2

FFMC    DMC     DC   ISI  ...  monthnov  monthoct  monthsep  size_category
0    86.2   26.2   94.3   5.1  ...         0         0         0              1
1    90.6   35.4  669.1   6.7  ...         0         1         0              1
2    90.6   43.7  686.9   6.7  ...         0         1         0              1
3    91.7   33.3   77.5   9.0  ...         0         0         0              1
4    89.3   51.3  102.2   9.6  ...         0         0         0              1
..    ...    ...    ...   ...  ...       ...       ...       ...            ...
512  81.6   56.7  665.6   1.9  ...         0         0         0              0
513  81.6   56.7  665.6   1.9  ...         0         0         0              0
514  81.6   56.7  665.6   1.9  ...         0         0         0              0
515  94.4  146.0  614.7  11.3  ...         0         0         0              1
516  79.5    3.0  106.7   1.1  ...         1         0         0              1

[509 rows x 29 columns]

In [90]:
# define x & y variables
array= forest_df2.values
x= array[:,0:28]
y= array[:,28]

In [91]:
x

array([[ 86.2,  26.2,  94.3, ...,   0. ,   0. ,   0. ],
       [ 90.6,  35.4, 669.1, ...,   0. ,   1. ,   0. ],
       [ 90.6,  43.7, 686.9, ...,   0. ,   1. ,   0. ],
       ...,
       [ 81.6,  56.7, 665.6, ...,   0. ,   0. ,   0. ],
       [ 94.4, 146. , 614.7, ...,   0. ,   0. ,   0. ],
       [ 79.5,   3. , 106.7, ...,   1. ,   0. ,   0. ]])

In [92]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [93]:
#split data into train and test
X_train, X_test, Y_train,Y_test = train_test_split(x,y, test_size=0.3)

In [94]:
X_train.shape, X_test.shape, Y_train.shape,Y_test.shape

((356, 28), (153, 28), (356,), (153,))

In [95]:
# model building
clf = SVC()
param_grid = [{'kernel':['rbf', 'poly', 'linear'], 'gamma':[50,20, 10, 6, 5, 4, 0.5],'C':[15,14,13,12,11,10,9,1,0.1,0.01,0.001,0.0001]}]
gsv = GridSearchCV(clf, param_grid=param_grid, cv=10)
gsv.fit(X_train, Y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 9, 1, 0.1, 0.01, 0.001,
                                0.0001],
                          'gamma': [50, 20, 10, 6, 5, 4, 0.5],
                          'kernel': ['rbf', 'poly', 'linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [96]:
# Best parameters and best accuracy
gsv.best_params_, gsv.best_score_

({'C': 0.1, 'gamma': 50, 'kernel': 'linear'}, 0.9833333333333334)

**Prediction with best parameters**

In [97]:
clf= SVC( C=0.1, kernel='linear', gamma=50)
clf.fit(X_train, Y_train)
y_pred = clf.predict(X_test)
accuracy= accuracy_score(Y_test, y_pred)*100
print('Accuracy=', accuracy)
confusion_matrix(y_true=Y_test, y_pred= y_pred)


Accuracy= 98.69281045751634


array([[ 35,   2],
       [  0, 116]])